"""Auto migration

Revision ID: 630c2ce620bd
Revises: e406bb37ebed
Create Date: 2025-12-03 10:48:25.247109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '630c2ce620bd'
down_revision: Union[str, None] = 'e406bb37ebed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('tokens_consumed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'tokens_consumed')
    # ### end Alembic commands ###
