"""Auto migration

Revision ID: 6800e4fb6386
Revises: 630c2ce620bd
Create Date: 2026-01-02 15:43:55.782826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6800e4fb6386'
down_revision: Union[str, None] = '630c2ce620bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('agent_timezone', sa.String(length=100), server_default='UTC', nullable=True))
    op.add_column('conversations', sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('conversations', sa.Column('client_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('conversations', sa.Column('status', sa.String(), nullable=False, server_default='done'))
    op.add_column('conversations', sa.Column('conversation_config_override', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'conversation_config_override')
    op.drop_column('conversations', 'status')
    op.drop_column('conversations', 'client_data')
    op.drop_column('conversations', 'error_details')
    op.drop_column('agents', 'agent_timezone')
    # ### end Alembic commands ###
