"""Auto migration

Revision ID: 6851621fea9f
Revises: 1ab503e243b7
Create Date: 2025-09-23 11:39:58.942632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6851621fea9f'
down_revision: Union[str, None] = '1ab503e243b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_connections', sa.Column('widget_size', sa.String(), nullable=True))
    op.add_column('agent_connections', sa.Column('start_btn_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_connections', 'start_btn_color')
    op.drop_column('agent_connections', 'widget_size')
    # ### end Alembic commands ###
