"""added models for functions(agents)

Revision ID: 2006a5473bec
Revises: 371f171cced4
Create Date: 2026-02-02 12:36:21.920254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2006a5473bec'
down_revision: Union[str, Sequence[str], None] = '371f171cced4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('custom_voices_user_id_fkey', 'custom_voices', type_='foreignkey')
    op.create_foreign_key(None, 'custom_voices', 'unified_auth', ['user_id'], ['id'])
    op.add_column('function_api_config', sa.Column('function_id', sa.Integer(), nullable=False))
    op.add_column('function_api_config', sa.Column('endpoint_url', sa.String(), nullable=False))
    op.add_column('function_api_config', sa.Column('http_method', sa.Enum('get', 'post', 'put', 'delete', 'patch', name='requestmethodenum'), nullable=False))
    op.add_column('function_api_config', sa.Column('timeout_ms', sa.Integer(), nullable=False))
    op.add_column('function_api_config', sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('function_api_config', sa.Column('query_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('function_api_config', sa.Column('llm_response_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('function_api_config', sa.Column('response_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('function_api_config', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('function_api_config', sa.Column('modified_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'function_api_config', 'functions', ['function_id'], ['id'])
    op.add_column('functions', sa.Column('name', sa.String(), nullable=False))
    op.add_column('functions', sa.Column('description', sa.String(), nullable=False))
    op.add_column('functions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('functions', sa.Column('modified_at', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'functions', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'functions', type_='unique')
    op.drop_column('functions', 'modified_at')
    op.drop_column('functions', 'created_at')
    op.drop_column('functions', 'description')
    op.drop_column('functions', 'name')
    op.drop_constraint(None, 'function_api_config', type_='foreignkey')
    op.drop_column('function_api_config', 'modified_at')
    op.drop_column('function_api_config', 'created_at')
    op.drop_column('function_api_config', 'response_variables')
    op.drop_column('function_api_config', 'llm_response_schema')
    op.drop_column('function_api_config', 'query_params')
    op.drop_column('function_api_config', 'headers')
    op.drop_column('function_api_config', 'timeout_ms')
    op.drop_column('function_api_config', 'http_method')
    op.drop_column('function_api_config', 'endpoint_url')
    op.drop_column('function_api_config', 'function_id')
    op.drop_constraint(None, 'custom_voices', type_='foreignkey')
    op.create_foreign_key('custom_voices_user_id_fkey', 'custom_voices', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
