"""updated agent model user foreigen key

Revision ID: 371f171cced4
Revises: 55b6ac9b532f
Create Date: 2026-01-28 22:51:10.717321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '371f171cced4'
down_revision: Union[str, Sequence[str], None] = '55b6ac9b532f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('agents_user_id_fkey', 'agents', type_='foreignkey')
    op.create_foreign_key(None, 'agents', 'unified_auth', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.create_foreign_key('agents_user_id_fkey', 'agents', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
